### ISSUE TITLE
Feedback for "Service Creation Parameters"

### ISSUE THREAD

**Issue by chrisfries** [SAP-docs/btp-cloud-platform#167]
### Issue description

The Sample Code for `Method A` & `Combination of the two methods` does not work.
The paramaeter `path` has to be directly under `parameters` otherwise you will get the error: 

> Error parsing xs-security.json data: Unrecognized field "path" 

In additon `Method A` actually shows the combination method. Described is that with method A only the MTA deployment descriptor is used (without an extra json file)

Following the corrected sample codes:

**Method A**
```
resources:
  - name: java-uaa
    type: com.sap.xs.uaa
    parameters:
      config:
        xsappname: java-hello-world
```

**Combination of the two Methods**

```
resources:
  - name: java-uaa
    type: com.sap.xs.uaa
    parameters:
      path: <path to directory>
      config:
        xsappname: java-hello-world
        
```

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Service Creation Parameters

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/service-creation-parameters
